---
title: "Covid-19"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: lumen
---


```{r setup, include=FALSE}
library(dplyr)
library(highcharter)
library(reshape2)
library(flexdashboard)
library(janitor)

covid = data.table::fread('https://covid.ourworldindata.org/data/owid-covid-data.csv') %>% 
  mutate(date = as.Date(date)) %>% filter(!location %in% c('World','International'))
covid2= covid %>% filter(total_cases > 15e3)

parrr = covid %>% select(location,date,starts_with('total'),
                         population_density:life_expectancy,
                         -contains('smokers'),-contains('poverty'),
                         -contains('tests')) %>% 
  group_by(location) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% ungroup() %>% 
  select(-date)

parrr2 = purrr::map(seq(nrow(parrr)), function(x) {
  list(data = t(parrr[x,2:13]), name = paste(pull(parrr[x,1])))
})


deaths = covid %>% group_by(location) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% ungroup() %>% 
  select(continent,location,total_deaths)

#total = data.table::fread('files/total.csv')
prediction = data.table::fread('files/prediction.csv') %>% mutate(Date = as.Date(Date))
imp = data.table::fread('files/imp.csv') %>% mutate( relative_importance = round( relative_importance,3))


today = data.table::fread('https://covid.ourworldindata.org/data/owid-covid-data.csv') %>% 
  mutate(date = as.Date(date)) %>% filter(!location %in% c('World','International')) %>% 
  filter(location %in% 'Azerbaijan') %>% select(-c(1:3),-contains('test')) %>% 
  mutate(date=lag(date)) %>% filter(date >= '2020-03-11') %>% 
  .[nrow(.),] %>% .[,1:5]

```

Azerbaijan
=====================================  

Row {data-height=130}
-----------------------------------------------------------------------

### Date

```{r}
calen <- today$date
valueBox(calen, icon = "fa-calendar-alt",color = "danger")
```

### Total Cases

```{r}
tot_cases <- today$total_cases
valueBox(tot_cases, icon = "fa-users")
```

### Total Deaths

```{r}
tot_deaths <- today$total_deaths
valueBox(tot_deaths, icon = "fa-exclamation-triangle")
```

### New cases

```{r}
new_cases <- today$new_cases
valueBox(new_cases, 
         icon = "fa-diagnoses",
         color = "warning")
```

### New Deaths

```{r}
new_deaths <- today$new_deaths
valueBox(new_deaths, 
         icon = "fa-exclamation-circle",
         color = "danger")
```

Row {data-height=300}
-----------------------------------------------------------------------

### Monthly minimum and maximum

```{r}
covid = data.table::fread('https://covid.ourworldindata.org/data/owid-covid-data.csv') %>% 
  mutate(date = as.Date(date)) %>% filter(!location %in% c('World','International')) %>% 
  filter(location %in% 'Azerbaijan') %>% select(-c(1:3),-contains('test')) %>% 
  mutate(date=lag(date)) %>% filter(date >= '2020-03-11') 

covid$new_cases[100]=438
covid$new_cases[101]=471

covid = covid %>% mutate(new_cases = case_when(
  date == '2020-03-12' ~ 4,
  date == '2020-03-15' ~ 3,
  date == '2020-03-16' ~ 3,
  date == '2020-03-20' ~ 4,
  TRUE ~ new_cases
)) %>% rbind(covid[3,] %>% mutate(date = as.Date('2020-03-14'),
                                  new_cases = 19) ) 

#covid = covid %>% mutate(#new_cases = lag(new_cases,10)
#                         date = date - 3)

total = covid %>% select(-contains('total')) 
names(total)[2]='value'

total = Filter(function(x)(length(unique(x))>1), total) 


total = total %>% arrange(date) 

total$value[69]=113
total$value[70]=131

min_month = total %>% select(date,value,new_deaths) %>% 
  group_by(lubridate::month(date)) %>% 
  summarise_all(list(min)) %>% .[2:4]

names(min_month)[2:3]=paste('min',names(min_month)[2:3],sep='_')

max_month = total %>% select(date,value,new_deaths) %>% 
  group_by(lubridate::month(date)) %>% 
  summarise_all(list(max)) %>% .[2:4]

names(max_month)[2:3]=paste('max',names(max_month)[2:3],sep='_')

all_month = cbind(min_month[2:3],max_month) %>% select(date,everything()) 

date_len = lubridate::month(all_month$date)



all_month$date = seq(as.Date(paste('2020-0', min(date_len),'-01',sep = '')),
                     as.Date(paste('2020-0', max(date_len),'-01',sep = '')),'month')


hchart(all_month, type = "columnrange",name = 'New cases',
       color='red',
       hcaes(x = date, low = min_value, high = max_value)) %>% 
  hc_yAxis(title=list(text='Monthly New Cases')) %>% 
  hc_xAxis(title=list(text='Date'),
           labels=list(
             formatter = JS("
                            function() {
          return Highcharts.dateFormat('%b', this.value);
        }
                            ")
           )) %>% 
  hc_plotOptions(columnrange = list(dataLabels = list(
    enabled=T,
    #format= '{y} new cases',
    formatter = JS("
                   function() {
            if (this.y === this.point.low) {
              return 'min: ' + this.y;
            }
            if (this.y === this.point.high) {
              return 'max: ' + this.y;
            }
            return 'blah';
          }
                   ")
  ))) %>% hc_chart(inverted=T) %>% hc_add_theme(hc_theme_google())
```


### Daily new and death cases

```{r}

covid = data.table::fread('https://covid.ourworldindata.org/data/owid-covid-data.csv') %>% 
  mutate(date = as.Date(date)) %>% filter(!location %in% c('World','International')) %>% 
  filter(location %in% 'Azerbaijan') %>% select(-c(1:3),-contains('test')) %>% 
  mutate(date=lag(date)) %>% filter(date >= '2020-03-11') 

covid$new_cases[100]=438
covid$new_cases[101]=471

covid = covid %>% mutate(new_cases = case_when(
  date == '2020-03-12' ~ 4,
  date == '2020-03-15' ~ 3,
  date == '2020-03-16' ~ 3,
  date == '2020-03-20' ~ 4,
  TRUE ~ new_cases
)) %>% rbind(covid[3,] %>% mutate(date = as.Date('2020-03-14'),
                                  new_cases = 19) ) 

#covid = covid %>% mutate(#new_cases = lag(new_cases,10)
#                         date = date - 3)

total = covid %>% select(-contains('total')) 
names(total)[2]='value'

total = Filter(function(x)(length(unique(x))>1), total) 


total = total %>% arrange(date) 

total$value[69]=113
total$value[70]=131


tot <- melt(total %>% select(date,value,new_deaths) %>% 
              rename(new_cases = value), id="date")



hchart(tot,'areaspline',hcaes(x = date, y = value, group = variable)) %>% 
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
             shared = TRUE, borderWidth = 5) %>% 
  hc_colors(c("#000000", "red")) %>% 
  hc_title(align = "left", style = list(color = "black")) %>% 
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>% 
  hc_tooltip(sort = TRUE, table = TRUE) %>% 
  hc_legend(align = "right", verticalAlign = "top", layout = "horizontal") %>% 
  hc_xAxis(
    opposite = TRUE,
    gridLineWidth = 0,
    title = list(text = "Date", style = list(color = "black")),
    lineColor = "black", tickColor = "black",
    labels = list(style = list(color = "black"))
  ) %>% 
  hc_yAxis(
    reversed = TRUE, 
    gridLineWidth = 0, 
    lineWidth = 1,
    lineColor = "black",
    tickWidth = 1,
    tickLength = 10, 
    tickColor = "black",
    title = list(text = "New cases & Death rate", style = list(color = "black")),
    labels = list(style = list(color = "black"))
  ) %>% 
  hc_add_theme(hc_theme_google()) %>% hc_title(text='')

```



Row {.tabset data-height=350}
-----------------------------------------------------------------------

### Future prediction

```{r}

df_m <- melt(prediction, id="Date")

hchart(df_m, "line", hcaes(x = Date, y = value, group = variable)) %>% 
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
             shared = TRUE, borderWidth = 5)  %>% hc_colors(c('red','darkgreen')) %>% 
  hc_xAxis(
    opposite = F,
    plotLines = list(
      list(label = list(text = "Test data",rotation=90, textAlign = 'left'),
           color = "#FCFFC5",
           width = 2,
           from = datetime_to_timestamp(as.Date('2020-07-05',tz='UTC')),
           to = datetime_to_timestamp(as.Date('2020-07-22',tz='UTC'))
      ),
      list(label = list(text = "Train data",rotation=90, textAlign = 'left'),
           color = "#ffcccc",
           width = 2,
           from = datetime_to_timestamp(as.Date('2020-03-11',tz='UTC')),
           to = datetime_to_timestamp(as.Date('2020-07-04',tz='UTC'))
      ),
      list(label = list(text = "Prediction",rotation=90, textAlign = 'left'),
           color = "#ccff99",
           width = 2,
           from = datetime_to_timestamp(as.Date('2020-07-23',tz='UTC')),
           to = datetime_to_timestamp(as.Date('2020-09-30',tz='UTC'))
      )
    )
  ) %>% 
  hc_add_theme(hc_theme_google())


```

### Explanation

The prediction was made by Neural Networks.

There is an experimental prediction part for daily COVID-19 cases:

1) It covers the period from March 11 till July 22

2) The model needs more fresh data to get better

3) Besides daily cases, we included valuable attributes such as SMS permission, traffic/subway/bus, and other restrictions.

SMS permission and its restriction time (2-3 hours) are among the topmost important variables. 

### Top important vars

```{r}
hchart(imp, "treemap", hcaes(x = variable, value = relative_importance,color= 20:1)) %>% 
  hc_legend(enabled=F)
```

Worldwide
=====================================  

Row {data-height=420}
-----------------------------------------------------------------------

### Total Deaths

```{r}

highchart() %>%
  hc_chart(type = 'packedbubble') %>%
  hc_add_theme(hc_theme_flatdark()) %>% 
  hc_tooltip(useHTML = T, pointFormat = '{point.name}: {point.value}') %>%
  hc_plotOptions(packedbubble = list(
    dataLabels = list(enabled=T,
                      format= '{point.name}'),
    minSize = '20%',
    maxSize = '50%',
    zMin = 0,
    zMax = 1000,
    layoutAlgorithm = list(
      gravitationalConstant = 0.10,
      splitSeries = T,
      seriesInteraction = F,
      dragBetweenSeries = T,
      parentNodeLimit = T
    )
  )
  ) %>%
  hc_legend(enabled = T) %>%
  hc_exporting(enabled = F) %>%
  hc_add_series(name = 'Asia', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='Asia'))), function(x) {
                    list(name = deaths %>% filter(continent=='Asia') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='Asia') %>% .[x,3] %>% pull(),
                         description = 'Asia')
                  })
  ) %>%
  hc_add_series(name = 'Europe', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='Europe'))), function(x) {
                    list(name = deaths %>% filter(continent=='Europe') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='Europe') %>% .[x,3] %>% pull(),
                         description = 'Europe')
                  })
  ) %>%
  hc_add_series(name = 'Africa', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='Africa'))), function(x) {
                    list(name = deaths %>% filter(continent=='Africa') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='Africa') %>% .[x,3] %>% pull(),
                         description = 'Africa')
                  })
  ) %>% 
  hc_add_series(name = 'North America', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='North America'))), function(x) {
                    list(name = deaths %>% filter(continent=='North America') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='North America') %>% .[x,3] %>% pull(),
                         description = 'North America')
                  })
  ) %>% 
  hc_add_series(name = 'South America', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='South America'))), function(x) {
                    list(name = deaths %>% filter(continent=='South America') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='South America') %>% .[x,3] %>% pull(),
                         description = 'South America')
                  })
  ) %>% 
  hc_add_series(name = 'Oceania', 
                data = 
                  purrr::map(seq(nrow(deaths %>% filter(continent=='Oceania'))), function(x) {
                    list(name = deaths %>% filter(continent=='Oceania') %>% .[x,2] %>% pull(),
                         value = deaths %>% filter(continent=='Oceania') %>% .[x,3] %>% pull(),
                         description = 'Oceania')
                  })
  )

```


Row {data-height=350}
-----------------------------------------------------------------------

### General view

```{r}
highchart() %>% hc_chart(type= 'spline',
                         parallelCoordinates=T,
                         parallelAxes=list(
                           lineWidth= 5
                         )) %>% 
  hc_xAxis(categories=colnames(parrr[2:15]),offset=10) %>% 
  hc_yAxis_multiples( list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}'),
                     list(min= 0,tooltipValueFormat= '{value}')) %>% 
  hc_colors('rgba(14, 200, 200, 0.2)') %>% 
  hc_add_theme(hc_theme_google()) %>% 
  hc_plotOptions(series = list(marker = list(enabled = F))) %>% 
  hc_add_series_list(parrr2) %>% 
  hc_plotOptions(
    series=list(
      animation=F,
      marker=list(
        enabled=F,
        states=list(
          hover=list(
            enabled=F
          )
        )
      ),
      states= list(
        hover=list(
          halo=list(
            size= 0
          )
        )
      )
    ) )
```

### New cases

```{r}
hchart(covid2, "streamgraph", hcaes(date, new_cases, group = location)) %>% 
  hc_yAxis(visible = FALSE) %>% 
  hc_plotOptions(series = list(label = list(minFontSize=2,enabled=T,
                                            maxFontSize=15,style= list(color= 'white'),
                                            fontWeight='bold'))) %>% 
  hc_legend(enabled=F)  %>% hc_yAxis(visible=F,startOnTick=F,endOnTick=F) %>% 
  hc_xAxis(maxPadding= 0,lineWidth= 0,margin= 0,tickWidth= 0,crosshair=T) %>% 
  hc_annotations(labels= list(point=list(x=61,xAxis= 0, y= 600, yAxis= 0),
           text='The first case in Azerbaijan'),
           labelOptions=list(backgroundColor= 'rgba(255,255,255,0.5)',
                             borderColor= 'silver')) %>% 
  #hc_title(text=paste('New cases ',max(covid2$date, na.rm = T))) %>% 
  hc_add_theme(hc_theme_google()) %>% 
  hc_colors(colors = scales::viridis_pal(option = "B", end = 0.7)(covid2$location %>% unique() %>% length()))

```

